[package]
name = "ftls-server"
version = "0.1.0"
edition = "2024"
license.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"


[dependencies]
anyhow = { workspace = true }
tun = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
tracing = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
ftls-lib = { path = "../ftls-lib" }
tracing-subscriber = "0.3.23"
tokio = { version = "1.52.0", features = [
  "net",
  "io-util",
  "macros",
  "rt-multi-thread",
  "time",
  "fs",
] }
tokio-rustls = "0.26.4"
webpki-roots = "1.0.7"
fast-socks5 = "1.0.0"
clap = { version = "4.6.1", features = ["derive"] }
hickory-resolver = { version = "0.26.0", features = [
  "rustls-platform-verifier",
] }
uuid = { version = "1.23.1", features = ["v4", "fast-rng"] }
tracing-forest = { version = "0.3.1", features = ["full"] }

[dev-dependencies]
rcgen = "0.14.7"
